<?php

namespace Database\Seeders;

use App\Models\LabTest;
use Illuminate\Database\Seeder;

/**
 * Master Lab Test Seeder - Based on Lab Report Files
 * 
 * This seeder contains all lab tests extracted from the lab report folder.
 * Tests are organized by category with proper reference ranges and parameters.
 * 
 * Categories:
 * 1. Hematology Tests
 * 2. Biochemistry Tests
 * 3. Serology/Immunology Tests
 * 4. Coagulation Tests
 * 5. Microbiology/Culture Tests
 * 6. Molecular/PCR Tests
 * 7. Urine Tests
 * 8. Stool Tests
 * 9. Semen Analysis
 * 10. Special Tests
 */
class LabReportMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $labTests = array_merge(
            $this->getHematologyTests(),
            $this->getBiochemistryTests(),
            $this->getSerologyTests(),
            $this->getCoagulationTests(),
            $this->getMicrobiologyTests(),
            $this->getMolecularTests(),
            $this->getUrineTests(),
            $this->getStoolTests(),
            $this->getSemenTests(),
            $this->getSpecialTests()
        );

        $count = 0;
        foreach ($labTests as $test) {
            LabTest::updateOrCreate(
                ['test_code' => $test['test_code']],
                $test
            );
            $count++;
        }

        $this->command->info("Lab Report Master Seeder completed successfully!");
        $this->command->info("Total tests seeded: {$count}");
    }

    /**
     * Hematology Tests
     */
    private function getHematologyTests(): array
    {
        return [
            [
                'test_code' => 'CBC',
                'name' => 'Complete Blood Count (CBC)',
                'category' => 'Hematology',
                'description' => 'Comprehensive blood test analyzing red blood cells, white blood cells, and platelets',
                'procedure' => 'Blood sample collection and automated analysis using hematology analyzer',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 80.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'WBC: 4.5-11.0, RBC: 4.5-5.5, HGB: 13.5-17.5, Platelets: 150-400',
                'reference_ranges' => json_encode(['wbc' => ['min' => 4.5, 'max' => 11.0, 'unit' => 'x10³/μL'], 'rbc' => ['min' => 4.5, 'max' => 5.5, 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['min' => 13.5, 'max' => 17.5, 'unit' => 'g/dL'], 'hematocrit' => ['min' => 38, 'max' => 50, 'unit' => '%'], 'platelets' => ['min' => 150, 'max' => 400, 'unit' => 'x10³/μL']]),
                'parameters' => json_encode(['wbc' => ['name' => 'White Blood Cells', 'unit' => 'x10³/μL'], 'rbc' => ['name' => 'Red Blood Cells', 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['name' => 'Hemoglobin', 'unit' => 'g/dL'], 'hematocrit' => ['name' => 'Hematocrit', 'unit' => '%'], 'platelets' => ['name' => 'Platelets', 'unit' => 'x10³/μL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CBC-BHA-M',
                'name' => 'CBC BHA 3000 (Adult Male)',
                'category' => 'Hematology',
                'description' => 'Complete Blood Count using BHA 3000 analyzer for adult males',
                'procedure' => 'Automated hematology analysis using BHA 3000 analyzer',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 100.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'WBC: 4.5-11.0, RBC: 4.5-5.5, HGB: 13.5-17.5, HCT: 40-50%',
                'reference_ranges' => json_encode(['wbc' => ['min' => 4.5, 'max' => 11.0, 'unit' => 'x10³/μL'], 'rbc' => ['min' => 4.5, 'max' => 5.5, 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['min' => 13.5, 'max' => 17.5, 'unit' => 'g/dL'], 'hematocrit' => ['min' => 40, 'max' => 50, 'unit' => '%']]),
                'parameters' => json_encode(['wbc' => ['name' => 'White Blood Cells', 'unit' => 'x10³/μL'], 'rbc' => ['name' => 'Red Blood Cells', 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['name' => 'Hemoglobin', 'unit' => 'g/dL'], 'hematocrit' => ['name' => 'Hematocrit', 'unit' => '%']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CBC-BHA-F',
                'name' => 'CBC BHA 3000 (Adult Female)',
                'category' => 'Hematology',
                'description' => 'Complete Blood Count using BHA 3000 analyzer for adult females',
                'procedure' => 'Automated hematology analysis using BHA 3000 analyzer',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 100.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'WBC: 4.5-11.0, RBC: 4.0-5.0, HGB: 12.0-16.0, HCT: 36-46%',
                'reference_ranges' => json_encode(['wbc' => ['min' => 4.5, 'max' => 11.0, 'unit' => 'x10³/μL'], 'rbc' => ['min' => 4.0, 'max' => 5.0, 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['min' => 12.0, 'max' => 16.0, 'unit' => 'g/dL'], 'hematocrit' => ['min' => 36, 'max' => 46, 'unit' => '%']]),
                'parameters' => json_encode(['wbc' => ['name' => 'White Blood Cells', 'unit' => 'x10³/μL'], 'rbc' => ['name' => 'Red Blood Cells', 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['name' => 'Hemoglobin', 'unit' => 'g/dL'], 'hematocrit' => ['name' => 'Hematocrit', 'unit' => '%']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CBC-BHA-C',
                'name' => 'CBC BHA 3000 (Children)',
                'category' => 'Hematology',
                'description' => 'Complete Blood Count using BHA 3000 analyzer for children',
                'procedure' => 'Automated hematology analysis using BHA 3000 analyzer',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 100.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'Age-dependent reference ranges',
                'reference_ranges' => json_encode(['wbc' => ['min' => 5.0, 'max' => 15.0, 'unit' => 'x10³/μL'], 'rbc' => ['min' => 4.0, 'max' => 5.2, 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['min' => 11.0, 'max' => 16.0, 'unit' => 'g/dL'], 'hematocrit' => ['min' => 33, 'max' => 48, 'unit' => '%']]),
                'parameters' => json_encode(['wbc' => ['name' => 'White Blood Cells', 'unit' => 'x10³/μL'], 'rbc' => ['name' => 'Red Blood Cells', 'unit' => 'x10⁶/μL'], 'hemoglobin' => ['name' => 'Hemoglobin', 'unit' => 'g/dL'], 'hematocrit' => ['name' => 'Hematocrit', 'unit' => '%']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'BG',
                'name' => 'Blood Group & RH Typing',
                'category' => 'Hematology',
                'description' => 'Determination of ABO blood group and Rh factor',
                'procedure' => 'Serological testing using antisera',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 50.00,
                'turnaround_time' => 2,
                'unit' => 'N/A',
                'normal_values' => 'A, B, AB, O with Rh +ve or -ve',
                'reference_ranges' => json_encode(['abo' => ['values' => ['A', 'B', 'AB', 'O']], 'rh' => ['values' => ['Positive', 'Negative']]]),
                'parameters' => json_encode(['abo' => ['name' => 'ABO Blood Group', 'unit' => ''], 'rh' => ['name' => 'Rh Factor', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'BG-CHILD',
                'name' => 'Blood Group & RH (Child)',
                'category' => 'Hematology',
                'description' => 'Blood group determination for pediatric patients',
                'procedure' => 'Serological testing using antisera',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 50.00,
                'turnaround_time' => 2,
                'unit' => 'N/A',
                'normal_values' => 'A, B, AB, O with Rh +ve or -ve',
                'reference_ranges' => json_encode(['abo' => ['values' => ['A', 'B', 'AB', 'O']], 'rh' => ['values' => ['Positive', 'Negative']]]),
                'parameters' => json_encode(['abo' => ['name' => 'ABO Blood Group', 'unit' => ''], 'rh' => ['name' => 'Rh Factor', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'ESR',
                'name' => 'Erythrocyte Sedimentation Rate (ESR)',
                'category' => 'Hematology',
                'description' => 'Non-specific test for inflammation and tissue damage',
                'procedure' => 'Westergren method',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 100.00,
                'turnaround_time' => 4,
                'unit' => 'mm/hr',
                'normal_values' => 'Male: 0-15, Female: 0-20 mm/hr',
                'reference_ranges' => json_encode(['male' => ['min' => 0, 'max' => 15, 'unit' => 'mm/hr'], 'female' => ['min' => 0, 'max' => 20, 'unit' => 'mm/hr']]),
                'parameters' => json_encode(['esr' => ['name' => 'ESR', 'unit' => 'mm/hr']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HB',
                'name' => 'Hemoglobin (HB)',
                'category' => 'Hematology',
                'description' => 'Measurement of hemoglobin concentration in blood',
                'procedure' => 'Automated blood analyzer',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 50.00,
                'turnaround_time' => 2,
                'unit' => 'g/dL',
                'normal_values' => 'Male: 13-18, Female: 12-16, Child: 11-16 g/dL',
                'reference_ranges' => json_encode(['male' => ['min' => 13, 'max' => 18, 'unit' => 'g/dL'], 'female' => ['min' => 12, 'max' => 16, 'unit' => 'g/dL'], 'child' => ['min' => 11, 'max' => 16, 'unit' => 'g/dL']]),
                'parameters' => json_encode(['hemoglobin' => ['name' => 'Hemoglobin', 'unit' => 'g/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'TLC',
                'name' => 'Total Leukocyte Count (TLC)',
                'category' => 'Hematology',
                'description' => 'Total count of white blood cells',
                'procedure' => 'Automated hematology analyzer',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 50.00,
                'turnaround_time' => 2,
                'unit' => 'x10³/μL',
                'normal_values' => '4.5-11.0 x10³/μL',
                'reference_ranges' => json_encode(['tlc' => ['min' => 4.5, 'max' => 11.0, 'unit' => 'x10³/μL']]),
                'parameters' => json_encode(['tlc' => ['name' => 'Total Leukocyte Count', 'unit' => 'x10³/μL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'DLC',
                'name' => 'Differential Leukocyte Count (DLC)',
                'category' => 'Hematology',
                'description' => 'Count of different types of white blood cells',
                'procedure' => 'Automated analyzer or manual differential count',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 80.00,
                'turnaround_time' => 4,
                'unit' => '%',
                'normal_values' => 'Neutrophils: 50-70%, Lymphocytes: 20-40%, Monocytes: 2-10%, Eosinophils: 1-6%, Basophils: 0-1%',
                'reference_ranges' => json_encode(['neutrophils' => ['min' => 50, 'max' => 70, 'unit' => '%'], 'lymphocytes' => ['min' => 20, 'max' => 40, 'unit' => '%'], 'monocytes' => ['min' => 2, 'max' => 10, 'unit' => '%'], 'eosinophils' => ['min' => 1, 'max' => 6, 'unit' => '%'], 'basophils' => ['min' => 0, 'max' => 1, 'unit' => '%']]),
                'parameters' => json_encode(['neutrophils' => ['name' => 'Neutrophils', 'unit' => '%'], 'lymphocytes' => ['name' => 'Lymphocytes', 'unit' => '%'], 'monocytes' => ['name' => 'Monocytes', 'unit' => '%'], 'eosinophils' => ['name' => 'Eosinophils', 'unit' => '%'], 'basophils' => ['name' => 'Basophils', 'unit' => '%']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'MP',
                'name' => 'Malarial Parasites (MP)',
                'category' => 'Hematology',
                'description' => 'Detection of malaria parasites in blood smear',
                'procedure' => 'Thin and thick blood smear examination with Giemsa stain',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 50.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'No parasites seen',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['result' => ['name' => 'Malarial Parasites', 'unit' => ''], 'species' => ['name' => 'Species', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'RET',
                'name' => 'Reticulocytes Count',
                'category' => 'Hematology',
                'description' => 'Count of immature red blood cells',
                'procedure' => 'Blood smear staining and microscopic examination',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 350.00,
                'turnaround_time' => 8,
                'unit' => '%',
                'normal_values' => '0.5-2.5%',
                'reference_ranges' => json_encode(['reticulocytes' => ['min' => 0.5, 'max' => 2.5, 'unit' => '%']]),
                'parameters' => json_encode(['reticulocytes' => ['name' => 'Reticulocytes', 'unit' => '%']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'SMR',
                'name' => 'Special Smear',
                'category' => 'Hematology',
                'description' => 'Detailed microscopic examination of blood cells',
                'procedure' => 'Blood smear preparation and microscopic examination',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 200.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Normal RBC, WBC morphology',
                'reference_ranges' => json_encode(['morphology' => ['values' => ['Normal', 'Abnormal']]]),
                'parameters' => json_encode(['rbc_morphology' => ['name' => 'RBC Morphology', 'unit' => ''], 'wbc_morphology' => ['name' => 'WBC Morphology', 'unit' => ''], 'platelets' => ['name' => 'Platelets Assessment', 'unit' => '']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Biochemistry Tests
     */
    private function getBiochemistryTests(): array
    {
        return [
            [
                'test_code' => 'FBS',
                'name' => 'Fasting Blood Sugar (FBS)',
                'category' => 'Biochemistry',
                'description' => 'Measurement of blood glucose after 8-12 hours fasting',
                'procedure' => 'Glucose oxidase method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 100.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => '70-100 mg/dL',
                'reference_ranges' => json_encode(['fbs' => ['min' => 70, 'max' => 100, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['glucose' => ['name' => 'Fasting Glucose', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'RBS',
                'name' => 'Random Blood Sugar (RBS)',
                'category' => 'Biochemistry',
                'description' => 'Measurement of blood glucose at any time',
                'procedure' => 'Glucose oxidase method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 100.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => '<140 mg/dL',
                'reference_ranges' => json_encode(['rbs' => ['min' => 70, 'max' => 140, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['glucose' => ['name' => 'Random Glucose', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'GTT',
                'name' => 'Glucose Tolerance Test (GTT)',
                'category' => 'Biochemistry',
                'description' => 'Measures body response to sugar over 2 hours',
                'procedure' => 'Blood glucose measured fasting, then at 1hr and 2hr after glucose load',
                'sample_type' => 'Blood (Serum)',
                'cost' => 300.00,
                'turnaround_time' => 4,
                'unit' => 'mg/dL',
                'normal_values' => 'Fasting: <100, 1hr: <180, 2hr: <140 mg/dL',
                'reference_ranges' => json_encode(['fasting' => ['min' => 70, 'max' => 100, 'unit' => 'mg/dL'], '1hr' => ['min' => 70, 'max' => 180, 'unit' => 'mg/dL'], '2hr' => ['min' => 70, 'max' => 140, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['fasting' => ['name' => 'Fasting Glucose', 'unit' => 'mg/dL'], '1hr' => ['name' => '1 Hour Glucose', 'unit' => 'mg/dL'], '2hr' => ['name' => '2 Hour Glucose', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HBA1C',
                'name' => 'Hemoglobin A1C (HbA1C)',
                'category' => 'Biochemistry',
                'description' => 'Average blood glucose level over past 2-3 months',
                'procedure' => 'HPLC method',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 400.00,
                'turnaround_time' => 4,
                'unit' => '%',
                'normal_values' => '<5.7%',
                'reference_ranges' => json_encode(['hba1c' => ['min' => 4.0, 'max' => 5.7, 'unit' => '%']]),
                'parameters' => json_encode(['hba1c' => ['name' => 'Hemoglobin A1C', 'unit' => '%']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'LIPID',
                'name' => 'Lipid Profile',
                'category' => 'Biochemistry',
                'description' => 'Complete cholesterol panel',
                'procedure' => 'Enzymatic colorimetric method',
                'sample_type' => 'Blood (Serum) - 12 hours fasting',
                'cost' => 400.00,
                'turnaround_time' => 4,
                'unit' => 'mg/dL',
                'normal_values' => 'Total Chol: <200, TG: <150, HDL: >40, LDL: <100, VLDL: <30',
                'reference_ranges' => json_encode(['total_cholesterol' => ['min' => 0, 'max' => 200, 'unit' => 'mg/dL'], 'triglycerides' => ['min' => 0, 'max' => 150, 'unit' => 'mg/dL'], 'hdl' => ['min' => 40, 'max' => 100, 'unit' => 'mg/dL'], 'ldl' => ['min' => 0, 'max' => 100, 'unit' => 'mg/dL'], 'vldl' => ['min' => 0, 'max' => 30, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['total_cholesterol' => ['name' => 'Total Cholesterol', 'unit' => 'mg/dL'], 'triglycerides' => ['name' => 'Triglycerides', 'unit' => 'mg/dL'], 'hdl' => ['name' => 'HDL Cholesterol', 'unit' => 'mg/dL'], 'ldl' => ['name' => 'LDL Cholesterol', 'unit' => 'mg/dL'], 'vldl' => ['name' => 'VLDL Cholesterol', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'LFT',
                'name' => 'Liver Function Test (LFT)',
                'category' => 'Biochemistry',
                'description' => 'Comprehensive liver panel',
                'procedure' => 'Colorimetric and enzymatic methods',
                'sample_type' => 'Blood (Serum)',
                'cost' => 500.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'SGPT: 7-56, SGOT: 5-40, ALP: 44-147, Bilirubin: 0.1-1.2',
                'reference_ranges' => json_encode(['sgpt' => ['min' => 7, 'max' => 56, 'unit' => 'U/L'], 'sgot' => ['min' => 5, 'max' => 40, 'unit' => 'U/L'], 'alp' => ['min' => 44, 'max' => 147, 'unit' => 'U/L'], 'total_bilirubin' => ['min' => 0.1, 'max' => 1.2, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['sgpt' => ['name' => 'SGPT (ALT)', 'unit' => 'U/L'], 'sgot' => ['name' => 'SGOT (AST)', 'unit' => 'U/L'], 'alp' => ['name' => 'Alkaline Phosphatase', 'unit' => 'U/L'], 'total_bilirubin' => ['name' => 'Total Bilirubin', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'KFT',
                'name' => 'Kidney Function Test (RFT)',
                'category' => 'Biochemistry',
                'description' => 'Renal function panel',
                'procedure' => 'Colorimetric and enzymatic methods',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 4,
                'unit' => 'mg/dL',
                'normal_values' => 'Creatinine: 0.7-1.3, Urea: 15-40, BUN: 7-20, Uric Acid: 3.5-7.2',
                'reference_ranges' => json_encode(['creatinine' => ['min' => 0.7, 'max' => 1.3, 'unit' => 'mg/dL'], 'urea' => ['min' => 15, 'max' => 40, 'unit' => 'mg/dL'], 'bun' => ['min' => 7, 'max' => 20, 'unit' => 'mg/dL'], 'uric_acid' => ['min' => 3.5, 'max' => 7.2, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['creatinine' => ['name' => 'Serum Creatinine', 'unit' => 'mg/dL'], 'urea' => ['name' => 'Blood Urea', 'unit' => 'mg/dL'], 'bun' => ['name' => 'BUN', 'unit' => 'mg/dL'], 'uric_acid' => ['name' => 'Uric Acid', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CREAT',
                'name' => 'Serum Creatinine',
                'category' => 'Biochemistry',
                'description' => 'Measurement of creatinine level for kidney function',
                'procedure' => 'Jaffe method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 150.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => 'Male: 0.7-1.3, Female: 0.6-1.1 mg/dL',
                'reference_ranges' => json_encode(['male' => ['min' => 0.7, 'max' => 1.3, 'unit' => 'mg/dL'], 'female' => ['min' => 0.6, 'max' => 1.1, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['creatinine' => ['name' => 'Serum Creatinine', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'UREA',
                'name' => 'Blood Urea',
                'category' => 'Biochemistry',
                'description' => 'Measurement of urea nitrogen in blood',
                'procedure' => 'Berthelot method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 150.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => '15-40 mg/dL',
                'reference_ranges' => json_encode(['urea' => ['min' => 15, 'max' => 40, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['urea' => ['name' => 'Blood Urea', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'UA',
                'name' => 'Uric Acid',
                'category' => 'Biochemistry',
                'description' => 'Measurement of uric acid for gout assessment',
                'procedure' => 'Uricase method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 150.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => 'Male: 3.5-7.2, Female: 2.6-6.0 mg/dL',
                'reference_ranges' => json_encode(['male' => ['min' => 3.5, 'max' => 7.2, 'unit' => 'mg/dL'], 'female' => ['min' => 2.6, 'max' => 6.0, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['uric_acid' => ['name' => 'Uric Acid', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CA',
                'name' => 'Serum Calcium',
                'category' => 'Biochemistry',
                'description' => 'Measurement of total calcium in blood',
                'procedure' => 'O-cresolphthalein complexone method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => '8.5-10.5 mg/dL',
                'reference_ranges' => json_encode(['calcium' => ['min' => 8.5, 'max' => 10.5, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['calcium' => ['name' => 'Total Calcium', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'ELECTRO',
                'name' => 'Electrolytes Panel',
                'category' => 'Biochemistry',
                'description' => 'Sodium, Potassium, Chloride measurement',
                'procedure' => 'Ion selective electrode method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 350.00,
                'turnaround_time' => 2,
                'unit' => 'mEq/L',
                'normal_values' => 'Na: 135-145, K: 3.5-5.5, Cl: 95-105 mEq/L',
                'reference_ranges' => json_encode(['sodium' => ['min' => 135, 'max' => 145, 'unit' => 'mEq/L'], 'potassium' => ['min' => 3.5, 'max' => 5.5, 'unit' => 'mEq/L'], 'chloride' => ['min' => 95, 'max' => 105, 'unit' => 'mEq/L']]),
                'parameters' => json_encode(['sodium' => ['name' => 'Sodium', 'unit' => 'mEq/L'], 'potassium' => ['name' => 'Potassium', 'unit' => 'mEq/L'], 'chloride' => ['name' => 'Chloride', 'unit' => 'mEq/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CARDIAC',
                'name' => 'Cardiac Markers Panel',
                'category' => 'Biochemistry',
                'description' => 'CK-MB, Troponin I, LDH for myocardial infarction',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 800.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'CK-MB: <25, Troponin I: <0.04, LDH: 140-280',
                'reference_ranges' => json_encode(['ck_mb' => ['min' => 0, 'max' => 25, 'unit' => 'U/L'], 'troponin_i' => ['min' => 0, 'max' => 0.04, 'unit' => 'ng/mL'], 'ldh' => ['min' => 140, 'max' => 280, 'unit' => 'U/L']]),
                'parameters' => json_encode(['ck_mb' => ['name' => 'CK-MB', 'unit' => 'U/L'], 'troponin_i' => ['name' => 'Troponin I', 'unit' => 'ng/mL'], 'ldh' => ['name' => 'LDH', 'unit' => 'U/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'TROP-I',
                'name' => 'Troponin I',
                'category' => 'Biochemistry',
                'description' => 'Highly specific marker for myocardial damage',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 500.00,
                'turnaround_time' => 4,
                'unit' => 'ng/mL',
                'normal_values' => '<0.04 ng/mL',
                'reference_ranges' => json_encode(['troponin_i' => ['min' => 0, 'max' => 0.04, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['troponin_i' => ['name' => 'Troponin I', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'AMYL',
                'name' => 'Serum Amylase',
                'category' => 'Biochemistry',
                'description' => 'Pancreatic enzyme for pancreatitis diagnosis',
                'procedure' => 'Enzymatic method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 300.00,
                'turnaround_time' => 4,
                'unit' => 'U/L',
                'normal_values' => '30-110 U/L',
                'reference_ranges' => json_encode(['amylase' => ['min' => 30, 'max' => 110, 'unit' => 'U/L']]),
                'parameters' => json_encode(['amylase' => ['name' => 'Amylase', 'unit' => 'U/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'LIPASE',
                'name' => 'Serum Lipase',
                'category' => 'Biochemistry',
                'description' => 'More specific marker for pancreatitis',
                'procedure' => 'Enzymatic method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 4,
                'unit' => 'U/L',
                'normal_values' => '10-140 U/L',
                'reference_ranges' => json_encode(['lipase' => ['min' => 10, 'max' => 140, 'unit' => 'U/L']]),
                'parameters' => json_encode(['lipase' => ['name' => 'Lipase', 'unit' => 'U/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'SGPT',
                'name' => 'SGPT (ALT)',
                'category' => 'Biochemistry',
                'description' => 'Alanine aminotransferase for liver function',
                'procedure' => 'Kinetic method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 2,
                'unit' => 'U/L',
                'normal_values' => '7-56 U/L',
                'reference_ranges' => json_encode(['sgpt' => ['min' => 7, 'max' => 56, 'unit' => 'U/L']]),
                'parameters' => json_encode(['sgpt' => ['name' => 'SGPT (ALT)', 'unit' => 'U/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'SGOT',
                'name' => 'SGOT (AST)',
                'category' => 'Biochemistry',
                'description' => 'Aspartate aminotransferase for liver and heart',
                'procedure' => 'Kinetic method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 2,
                'unit' => 'U/L',
                'normal_values' => '5-40 U/L',
                'reference_ranges' => json_encode(['sgot' => ['min' => 5, 'max' => 40, 'unit' => 'U/L']]),
                'parameters' => json_encode(['sgot' => ['name' => 'SGOT (AST)', 'unit' => 'U/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'BIL-T',
                'name' => 'Total Bilirubin',
                'category' => 'Biochemistry',
                'description' => 'Measurement of total bilirubin for liver function',
                'procedure' => 'Diazo method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 150.00,
                'turnaround_time' => 2,
                'unit' => 'mg/dL',
                'normal_values' => '0.1-1.2 mg/dL',
                'reference_ranges' => json_encode(['total_bilirubin' => ['min' => 0.1, 'max' => 1.2, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['total_bilirubin' => ['name' => 'Total Bilirubin', 'unit' => 'mg/dL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'IRON',
                'name' => 'Iron Studies',
                'category' => 'Biochemistry',
                'description' => 'Serum Iron, TIBC, Ferritin for anemia workup',
                'procedure' => 'Colorimetric and chemiluminescent methods',
                'sample_type' => 'Blood (Serum)',
                'cost' => 500.00,
                'turnaround_time' => 8,
                'unit' => 'Various',
                'normal_values' => 'Iron: 60-170, TIBC: 250-450, Ferritin: 20-200',
                'reference_ranges' => json_encode(['serum_iron' => ['min' => 60, 'max' => 170, 'unit' => 'μg/dL'], 'tibc' => ['min' => 250, 'max' => 450, 'unit' => 'μg/dL'], 'ferritin' => ['min' => 20, 'max' => 200, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['serum_iron' => ['name' => 'Serum Iron', 'unit' => 'μg/dL'], 'tibc' => ['name' => 'TIBC', 'unit' => 'μg/dL'], 'ferritin' => ['name' => 'Ferritin', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'FERR',
                'name' => 'Ferritin',
                'category' => 'Biochemistry',
                'description' => 'Iron storage protein measurement',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 8,
                'unit' => 'ng/mL',
                'normal_values' => 'Male: 20-250, Female: 10-120 ng/mL',
                'reference_ranges' => json_encode(['male' => ['min' => 20, 'max' => 250, 'unit' => 'ng/mL'], 'female' => ['min' => 10, 'max' => 120, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['ferritin' => ['name' => 'Ferritin', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Serology/Immunology Tests
     */
    private function getSerologyTests(): array
    {
        return [
            [
                'test_code' => 'HBSAG',
                'name' => 'HBsAg (Hepatitis B Surface Antigen)',
                'category' => 'Serology',
                'description' => 'Screening test for Hepatitis B infection',
                'procedure' => 'Rapid chromatographic immunoassay or ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Non-reactive (Negative)',
                'reference_ranges' => json_encode(['result' => ['values' => ['Non-reactive', 'Reactive']]]),
                'parameters' => json_encode(['hbsag' => ['name' => 'HBsAg', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HCV-AB',
                'name' => 'HCV Antibody (Anti-HCV)',
                'category' => 'Serology',
                'description' => 'Screening test for Hepatitis C infection',
                'procedure' => 'Rapid immunoassay or ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Non-reactive (Negative)',
                'reference_ranges' => json_encode(['result' => ['values' => ['Non-reactive', 'Reactive']]]),
                'parameters' => json_encode(['hcv_ab' => ['name' => 'HCV Antibody', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HIV',
                'name' => 'HIV Screening',
                'category' => 'Serology',
                'description' => 'HIV-1 and HIV-2 antibody screening',
                'procedure' => 'Rapid immunoassay or ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Non-reactive (Negative)',
                'reference_ranges' => json_encode(['result' => ['values' => ['Non-reactive', 'Reactive']]]),
                'parameters' => json_encode(['hiv' => ['name' => 'HIV Antibody', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'VIRAL-PANEL',
                'name' => 'Viral Marker Panel (HBsAg, HCV, HIV)',
                'category' => 'Serology',
                'description' => 'Combined screening for Hepatitis B, C and HIV',
                'procedure' => 'Rapid immunoassays',
                'sample_type' => 'Blood (Serum)',
                'cost' => 500.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'All Non-reactive',
                'reference_ranges' => json_encode(['hbsag' => ['values' => ['Non-reactive', 'Reactive']], 'hcv' => ['values' => ['Non-reactive', 'Reactive']], 'hiv' => ['values' => ['Non-reactive', 'Reactive']]]),
                'parameters' => json_encode(['hbsag' => ['name' => 'HBsAg', 'unit' => ''], 'hcv' => ['name' => 'HCV Antibody', 'unit' => ''], 'hiv' => ['name' => 'HIV Antibody', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HPY-AG',
                'name' => 'H. pylori Antigen (Stool)',
                'category' => 'Serology',
                'description' => 'Detection of H. pylori antigen in stool',
                'procedure' => 'Rapid immunochromatographic assay',
                'sample_type' => 'Stool',
                'cost' => 300.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['h_pylori_ag' => ['name' => 'H. pylori Antigen', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HPY-AB',
                'name' => 'H. pylori Antibody (Serum)',
                'category' => 'Serology',
                'description' => 'Detection of H. pylori antibodies in blood',
                'procedure' => 'Rapid immunoassay or ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['h_pylori_ab' => ['name' => 'H. pylori Antibody', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'TYPH',
                'name' => 'Typhidot (IgG & IgM)',
                'category' => 'Serology',
                'description' => 'Rapid test for typhoid fever antibodies',
                'procedure' => 'Immunochromatographic assay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Both Negative',
                'reference_ranges' => json_encode(['igg' => ['values' => ['Negative', 'Positive']], 'igm' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['igg' => ['name' => 'Typhidot IgG', 'unit' => ''], 'igm' => ['name' => 'Typhidot IgM', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'WIDAL',
                'name' => 'Widal Test',
                'category' => 'Serology',
                'description' => 'Tube agglutination test for typhoid fever',
                'procedure' => 'Tube agglutination method',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 8,
                'unit' => 'Titer',
                'normal_values' => '<1:80 for all antigens',
                'reference_ranges' => json_encode(['o' => ['max' => 80, 'unit' => 'titer'], 'h' => ['max' => 80, 'unit' => 'titer'], 'ah' => ['max' => 80, 'unit' => 'titer'], 'bh' => ['max' => 80, 'unit' => 'titer']]),
                'parameters' => json_encode(['o' => ['name' => 'S. typhi O', 'unit' => 'titer'], 'h' => ['name' => 'S. typhi H', 'unit' => 'titer'], 'ah' => ['name' => 'S. paratyphi AH', 'unit' => 'titer'], 'bh' => ['name' => 'S. paratyphi BH', 'unit' => 'titer']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'ASO',
                'name' => 'ASO (Anti-Streptolysin O)',
                'category' => 'Serology',
                'description' => 'Test for streptococcal infection',
                'procedure' => 'Latex agglutination or turbidimetry',
                'sample_type' => 'Blood (Serum)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'IU/mL',
                'normal_values' => '<200 IU/mL',
                'reference_ranges' => json_encode(['aso' => ['min' => 0, 'max' => 200, 'unit' => 'IU/mL']]),
                'parameters' => json_encode(['aso' => ['name' => 'ASO Titer', 'unit' => 'IU/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CRP',
                'name' => 'C-Reactive Protein (CRP)',
                'category' => 'Serology',
                'description' => 'Acute phase reactant for inflammation',
                'procedure' => 'Latex agglutination or immunoturbidimetry',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 4,
                'unit' => 'mg/L',
                'normal_values' => '<6 mg/L',
                'reference_ranges' => json_encode(['crp' => ['min' => 0, 'max' => 6, 'unit' => 'mg/L']]),
                'parameters' => json_encode(['crp' => ['name' => 'CRP', 'unit' => 'mg/L']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'RF',
                'name' => 'Rheumatoid Factor (RF)',
                'category' => 'Serology',
                'description' => 'Test for rheumatoid arthritis',
                'procedure' => 'Latex agglutination or immunoturbidimetry',
                'sample_type' => 'Blood (Serum)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'IU/mL',
                'normal_values' => '<20 IU/mL',
                'reference_ranges' => json_encode(['rf' => ['min' => 0, 'max' => 20, 'unit' => 'IU/mL']]),
                'parameters' => json_encode(['rf' => ['name' => 'Rheumatoid Factor', 'unit' => 'IU/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CCP',
                'name' => 'Anti-CCP Antibodies',
                'category' => 'Serology',
                'description' => 'Specific test for rheumatoid arthritis',
                'procedure' => 'ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 800.00,
                'turnaround_time' => 24,
                'unit' => 'U/mL',
                'normal_values' => '<20 U/mL',
                'reference_ranges' => json_encode(['anti_ccp' => ['min' => 0, 'max' => 20, 'unit' => 'U/mL']]),
                'parameters' => json_encode(['anti_ccp' => ['name' => 'Anti-CCP', 'unit' => 'U/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'VDRL',
                'name' => 'VDRL',
                'category' => 'Serology',
                'description' => 'Screening test for syphilis',
                'procedure' => 'Flocculation test',
                'sample_type' => 'Blood (Serum)',
                'cost' => 200.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Non-reactive',
                'reference_ranges' => json_encode(['result' => ['values' => ['Non-reactive', 'Reactive']]]),
                'parameters' => json_encode(['vdrl' => ['name' => 'VDRL', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'BRU',
                'name' => 'Brucella IgG & IgM',
                'category' => 'Serology',
                'description' => 'Test for brucellosis',
                'procedure' => 'ELISA or Rapid test',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Both Negative',
                'reference_ranges' => json_encode(['igg' => ['values' => ['Negative', 'Positive']], 'igm' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['igg' => ['name' => 'Brucella IgG', 'unit' => ''], 'igm' => ['name' => 'Brucella IgM', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'TB-ICT',
                'name' => 'TB IgG & IgM (ICT)',
                'category' => 'Serology',
                'description' => 'Immunochromatographic test for tuberculosis antibodies',
                'procedure' => 'Rapid ICT',
                'sample_type' => 'Blood (Serum)',
                'cost' => 300.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Both Negative',
                'reference_ranges' => json_encode(['igg' => ['values' => ['Negative', 'Positive']], 'igm' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['igg' => ['name' => 'TB IgG', 'unit' => ''], 'igm' => ['name' => 'TB IgM', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'TOXO',
                'name' => 'Toxoplasma Test',
                'category' => 'Serology',
                'description' => 'Test for Toxoplasma gondii infection',
                'procedure' => 'ELISA or Rapid test',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['toxoplasma' => ['name' => 'Toxoplasma', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'TORCH',
                'name' => 'ToRCH Panel',
                'category' => 'Serology',
                'description' => 'Combined test for Toxoplasma, Rubella, CMV, HSV',
                'procedure' => 'ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 1200.00,
                'turnaround_time' => 24,
                'unit' => 'N/A',
                'normal_values' => 'All IgM Negative',
                'reference_ranges' => json_encode(['toxo_igm' => ['values' => ['Negative', 'Positive']], 'rub_igm' => ['values' => ['Negative', 'Positive']], 'cmv_igm' => ['values' => ['Negative', 'Positive']], 'hsv_igm' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['toxo_igm' => ['name' => 'Toxoplasma IgM', 'unit' => ''], 'rub_igm' => ['name' => 'Rubella IgM', 'unit' => ''], 'cmv_igm' => ['name' => 'CMV IgM', 'unit' => ''], 'hsv_igm' => ['name' => 'HSV IgM', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'LEISH',
                'name' => 'Leishmania Test',
                'category' => 'Serology',
                'description' => 'Test for Kala Azar (Visceral Leishmaniasis)',
                'procedure' => 'Rapid test or ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['leishmania' => ['name' => 'Leishmania', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HAV',
                'name' => 'HAV IgM (Hepatitis A)',
                'category' => 'Serology',
                'description' => 'Acute Hepatitis A infection marker',
                'procedure' => 'ELISA',
                'sample_type' => 'Blood (Serum)',
                'cost' => 300.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['hav_igm' => ['name' => 'HAV IgM', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'IGE',
                'name' => 'Total IgE',
                'category' => 'Serology',
                'description' => 'Total immunoglobulin E for allergy assessment',
                'procedure' => 'ELISA or nephelometry',
                'sample_type' => 'Blood (Serum)',
                'cost' => 400.00,
                'turnaround_time' => 8,
                'unit' => 'IU/mL',
                'normal_values' => '<100 IU/mL',
                'reference_ranges' => json_encode(['ige' => ['min' => 0, 'max' => 100, 'unit' => 'IU/mL']]),
                'parameters' => json_encode(['ige' => ['name' => 'Total IgE', 'unit' => 'IU/mL']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Coagulation Tests
     */
    private function getCoagulationTests(): array
    {
        return [
            [
                'test_code' => 'PT-INR',
                'name' => 'PT & INR',
                'category' => 'Coagulation',
                'description' => 'Prothrombin Time and International Normalized Ratio',
                'procedure' => 'Coagulometer using thromboplastin reagent',
                'sample_type' => 'Blood (Sodium Citrate)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'Seconds/Ratio',
                'normal_values' => 'PT: 11-14 seconds, INR: 0.9-1.1',
                'reference_ranges' => json_encode(['pt' => ['min' => 11, 'max' => 14, 'unit' => 'seconds'], 'inr' => ['min' => 0.9, 'max' => 1.1, 'unit' => 'ratio']]),
                'parameters' => json_encode(['pt' => ['name' => 'Prothrombin Time', 'unit' => 'seconds'], 'inr' => ['name' => 'INR', 'unit' => 'ratio']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'APTT',
                'name' => 'APTT (Activated Partial Thromboplastin Time)',
                'category' => 'Coagulation',
                'description' => 'Measures intrinsic pathway of coagulation',
                'procedure' => 'Coagulometer using activated partial thromboplastin reagent',
                'sample_type' => 'Blood (Sodium Citrate)',
                'cost' => 250.00,
                'turnaround_time' => 4,
                'unit' => 'Seconds',
                'normal_values' => '25-35 seconds',
                'reference_ranges' => json_encode(['aptt' => ['min' => 25, 'max' => 35, 'unit' => 'seconds']]),
                'parameters' => json_encode(['aptt' => ['name' => 'APTT', 'unit' => 'seconds']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'BTCT',
                'name' => 'Bleeding Time & Clotting Time',
                'category' => 'Coagulation',
                'description' => 'Manual test for platelet function and coagulation',
                'procedure' => 'Duke method for BT, Capillary tube method for CT',
                'sample_type' => 'Blood (Capillary)',
                'cost' => 150.00,
                'turnaround_time' => 4,
                'unit' => 'Minutes',
                'normal_values' => 'BT: 2-7, CT: 5-10 minutes',
                'reference_ranges' => json_encode(['bt' => ['min' => 2, 'max' => 7, 'unit' => 'minutes'], 'ct' => ['min' => 5, 'max' => 10, 'unit' => 'minutes']]),
                'parameters' => json_encode(['bt' => ['name' => 'Bleeding Time', 'unit' => 'minutes'], 'ct' => ['name' => 'Clotting Time', 'unit' => 'minutes']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'D-DIMER',
                'name' => 'D-Dimer',
                'category' => 'Coagulation',
                'description' => 'Fibrin degradation product for DVT/PE',
                'procedure' => 'Immunoturbidimetric assay',
                'sample_type' => 'Blood (Sodium Citrate)',
                'cost' => 500.00,
                'turnaround_time' => 4,
                'unit' => 'ng/mL',
                'normal_values' => '<500 ng/mL',
                'reference_ranges' => json_encode(['d_dimer' => ['min' => 0, 'max' => 500, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['d_dimer' => ['name' => 'D-Dimer', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Microbiology Tests
     */
    private function getMicrobiologyTests(): array
    {
        return [
            [
                'test_code' => 'BLOOD-CULT',
                'name' => 'Blood Culture',
                'category' => 'Microbiology',
                'description' => 'Detection of bacteria/fungi in blood',
                'procedure' => 'Aerobic and anaerobic culture using automated system',
                'sample_type' => 'Blood (Aseptic)',
                'cost' => 600.00,
                'turnaround_time' => 72,
                'unit' => 'N/A',
                'normal_values' => 'No growth',
                'reference_ranges' => json_encode(['result' => ['values' => ['No growth', 'Growth']]]),
                'parameters' => json_encode(['organism' => ['name' => 'Organism', 'unit' => ''], 'sensitivity' => ['name' => 'Antibiotic Sensitivity', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'URINE-CULT',
                'name' => 'Urine Culture & Sensitivity',
                'category' => 'Microbiology',
                'description' => 'Detection of UTI causing organisms',
                'procedure' => 'Culture on CLED and blood agar',
                'sample_type' => 'Urine (Mid-stream clean catch)',
                'cost' => 400.00,
                'turnaround_time' => 48,
                'unit' => 'CFU/mL',
                'normal_values' => '<1000 CFU/mL or No growth',
                'reference_ranges' => json_encode(['count' => ['max' => 1000, 'unit' => 'CFU/mL']]),
                'parameters' => json_encode(['organism' => ['name' => 'Organism', 'unit' => ''], 'count' => ['name' => 'Colony Count', 'unit' => 'CFU/mL'], 'sensitivity' => ['name' => 'Antibiotic Sensitivity', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'WOUND-CULT',
                'name' => 'Wound/Pus Culture',
                'category' => 'Microbiology',
                'description' => 'Identification of wound infection organisms',
                'procedure' => 'Culture on various media',
                'sample_type' => 'Pus/Wound swab',
                'cost' => 400.00,
                'turnaround_time' => 48,
                'unit' => 'N/A',
                'normal_values' => 'No significant growth',
                'reference_ranges' => json_encode(['result' => ['values' => ['No growth', 'Growth']]]),
                'parameters' => json_encode(['organism' => ['name' => 'Organism', 'unit' => ''], 'sensitivity' => ['name' => 'Antibiotic Sensitivity', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'CSF-EX',
                'name' => 'CSF Examination',
                'category' => 'Microbiology',
                'description' => 'Analysis of cerebrospinal fluid',
                'procedure' => 'Physical, chemical and microscopic examination',
                'sample_type' => 'CSF (Aseptic collection)',
                'cost' => 500.00,
                'turnaround_time' => 24,
                'unit' => 'Various',
                'normal_values' => 'Clear, Colorless, Glucose: 40-70, Protein: 15-45',
                'reference_ranges' => json_encode(['glucose' => ['min' => 40, 'max' => 70, 'unit' => 'mg/dL'], 'protein' => ['min' => 15, 'max' => 45, 'unit' => 'mg/dL']]),
                'parameters' => json_encode(['appearance' => ['name' => 'Appearance', 'unit' => ''], 'glucose' => ['name' => 'Glucose', 'unit' => 'mg/dL'], 'protein' => ['name' => 'Protein', 'unit' => 'mg/dL'], 'cells' => ['name' => 'Cell Count', 'unit' => '/mm3']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'PLEURAL',
                'name' => 'Pleural Fluid Examination',
                'category' => 'Microbiology',
                'description' => 'Analysis of fluid from pleural cavity',
                'procedure' => 'Physical, chemical and microscopic examination',
                'sample_type' => 'Pleural fluid',
                'cost' => 400.00,
                'turnaround_time' => 24,
                'unit' => 'Various',
                'normal_values' => 'Transudate characteristics',
                'reference_ranges' => json_encode(['protein' => ['max' => 3, 'unit' => 'g/dL'], 'ldh' => ['max' => 200, 'unit' => 'U/L']]),
                'parameters' => json_encode(['appearance' => ['name' => 'Appearance', 'unit' => ''], 'protein' => ['name' => 'Protein', 'unit' => 'g/dL'], 'glucose' => ['name' => 'Glucose', 'unit' => 'mg/dL'], 'ldh' => ['name' => 'LDH', 'unit' => 'U/L'], 'cells' => ['name' => 'Cell Count', 'unit' => '/mm3']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Molecular/PCR Tests
     */
    private function getMolecularTests(): array
    {
        return [
            [
                'test_code' => 'COVID-PCR',
                'name' => 'COVID-19 RNA PCR',
                'category' => 'Molecular',
                'description' => 'Molecular detection of SARS-CoV-2 RNA',
                'procedure' => 'Real-time RT-PCR',
                'sample_type' => 'Nasopharyngeal swab',
                'cost' => 800.00,
                'turnaround_time' => 24,
                'unit' => 'N/A',
                'normal_values' => 'Not detected',
                'reference_ranges' => json_encode(['result' => ['values' => ['Not Detected', 'Detected']]]),
                'parameters' => json_encode(['result' => ['name' => 'SARS-CoV-2 RNA', 'unit' => ''], 'ct_value' => ['name' => 'Ct Value', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HBV-DNA',
                'name' => 'HBV DNA PCR (Quantitative)',
                'category' => 'Molecular',
                'description' => 'Viral load quantification for Hepatitis B',
                'procedure' => 'Real-time PCR',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 2500.00,
                'turnaround_time' => 48,
                'unit' => 'IU/mL',
                'normal_values' => '<20 IU/mL (Undetectable)',
                'reference_ranges' => json_encode(['viral_load' => ['max' => 20, 'unit' => 'IU/mL']]),
                'parameters' => json_encode(['viral_load' => ['name' => 'HBV Viral Load', 'unit' => 'IU/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'HCV-RNA',
                'name' => 'HCV RNA PCR (Quantitative)',
                'category' => 'Molecular',
                'description' => 'Viral load quantification for Hepatitis C',
                'procedure' => 'Real-time PCR',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 2500.00,
                'turnaround_time' => 48,
                'unit' => 'IU/mL',
                'normal_values' => '<15 IU/mL (Undetectable)',
                'reference_ranges' => json_encode(['viral_load' => ['max' => 15, 'unit' => 'IU/mL']]),
                'parameters' => json_encode(['viral_load' => ['name' => 'HCV Viral Load', 'unit' => 'IU/mL'], 'genotype' => ['name' => 'Genotype', 'unit' => '']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Urine Tests
     */
    private function getUrineTests(): array
    {
        return [
            [
                'test_code' => 'URINE-R',
                'name' => 'Urine Routine Examination',
                'category' => 'Urine',
                'description' => 'Physical, chemical and microscopic analysis of urine',
                'procedure' => 'Dipstick analysis and microscopy',
                'sample_type' => 'Urine (Mid-stream)',
                'cost' => 100.00,
                'turnaround_time' => 2,
                'unit' => 'Various',
                'normal_values' => 'pH: 5-7, Specific gravity: 1.005-1.030, No protein/sugar',
                'reference_ranges' => json_encode(['ph' => ['min' => 5, 'max' => 7, 'unit' => ''], 'specific_gravity' => ['min' => 1.005, 'max' => 1.03, 'unit' => '']]),
                'parameters' => json_encode(['color' => ['name' => 'Color', 'unit' => ''], 'appearance' => ['name' => 'Appearance', 'unit' => ''], 'ph' => ['name' => 'pH', 'unit' => ''], 'specific_gravity' => ['name' => 'Specific Gravity', 'unit' => ''], 'protein' => ['name' => 'Protein', 'unit' => ''], 'glucose' => ['name' => 'Glucose', 'unit' => ''], 'rbc' => ['name' => 'RBC', 'unit' => '/HPF'], 'pus_cells' => ['name' => 'Pus Cells', 'unit' => '/HPF']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'URINE-CS',
                'name' => 'Urine C/S',
                'category' => 'Urine',
                'description' => 'Urine culture and sensitivity',
                'procedure' => 'Culture on CLED agar',
                'sample_type' => 'Urine (Mid-stream clean catch)',
                'cost' => 400.00,
                'turnaround_time' => 48,
                'unit' => 'CFU/mL',
                'normal_values' => '<1000 CFU/mL',
                'reference_ranges' => json_encode(['count' => ['max' => 1000, 'unit' => 'CFU/mL']]),
                'parameters' => json_encode(['organism' => ['name' => 'Organism', 'unit' => ''], 'count' => ['name' => 'Colony Count', 'unit' => 'CFU/mL'], 'sensitivity' => ['name' => 'Antibiotic Sensitivity', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'UPT',
                'name' => 'Urine Pregnancy Test',
                'category' => 'Urine',
                'description' => 'Detection of hCG hormone in urine',
                'procedure' => 'Immunochromatographic assay',
                'sample_type' => 'Urine (First morning)',
                'cost' => 150.00,
                'turnaround_time' => 1,
                'unit' => 'N/A',
                'normal_values' => 'Negative (Non-pregnant)',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['result' => ['name' => 'Pregnancy Test', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'FOBT',
                'name' => 'Occult Blood (FOBT)',
                'category' => 'Urine',
                'description' => 'Detection of hidden blood in stool',
                'procedure' => 'Guaiac-based or immunochemical test',
                'sample_type' => 'Stool',
                'cost' => 200.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['result' => ['name' => 'Occult Blood', 'unit' => '']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Stool Tests
     */
    private function getStoolTests(): array
    {
        return [
            [
                'test_code' => 'STOOL-R',
                'name' => 'Stool Routine Examination',
                'category' => 'Stool',
                'description' => 'Physical and microscopic examination of stool',
                'procedure' => 'Direct microscopy and concentration techniques',
                'sample_type' => 'Stool (Fresh)',
                'cost' => 100.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'No ova/cysts/parasites seen',
                'reference_ranges' => json_encode(['result' => ['values' => ['Normal', 'Abnormal']]]),
                'parameters' => json_encode(['color' => ['name' => 'Color', 'unit' => ''], 'consistency' => ['name' => 'Consistency', 'unit' => ''], 'blood' => ['name' => 'Blood', 'unit' => ''], 'mucus' => ['name' => 'Mucus', 'unit' => ''], 'ova' => ['name' => 'Ova', 'unit' => ''], 'cysts' => ['name' => 'Cysts', 'unit' => ''], 'parasites' => ['name' => 'Parasites', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'STOOL-OB',
                'name' => 'Stool Occult Blood',
                'category' => 'Stool',
                'description' => 'Detection of hidden blood in stool',
                'procedure' => 'Guaiac test or immunochemical test',
                'sample_type' => 'Stool',
                'cost' => 150.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['result' => ['name' => 'Occult Blood', 'unit' => '']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Semen Analysis
     */
    private function getSemenTests(): array
    {
        return [
            [
                'test_code' => 'SEMEN',
                'name' => 'Complete Semen Analysis',
                'category' => 'Semen',
                'description' => 'Comprehensive analysis of semen for fertility assessment',
                'procedure' => 'Macroscopic and microscopic examination',
                'sample_type' => 'Semen (After 2-5 days abstinence)',
                'cost' => 500.00,
                'turnaround_time' => 4,
                'unit' => 'Various',
                'normal_values' => 'Volume: >1.5mL, Count: >15 million/mL, Motility: >40%',
                'reference_ranges' => json_encode(['volume' => ['min' => 1.5, 'unit' => 'mL'], 'count' => ['min' => 15, 'unit' => 'million/mL'], 'motility' => ['min' => 40, 'unit' => '%'], 'morphology' => ['min' => 4, 'unit' => '%']]),
                'parameters' => json_encode(['volume' => ['name' => 'Volume', 'unit' => 'mL'], 'color' => ['name' => 'Color', 'unit' => ''], 'viscosity' => ['name' => 'Viscosity', 'unit' => ''], 'ph' => ['name' => 'pH', 'unit' => ''], 'count' => ['name' => 'Sperm Count', 'unit' => 'million/mL'], 'motility' => ['name' => 'Motility', 'unit' => '%'], 'morphology' => ['name' => 'Normal Morphology', 'unit' => '%']]),
                'status' => 'active',
            ],
        ];
    }

    /**
     * Special Tests
     */
    private function getSpecialTests(): array
    {
        return [
            [
                'test_code' => 'CROSS-MATCH',
                'name' => 'Cross Match (Blood Transfusion)',
                'category' => 'Special',
                'description' => 'Compatibility testing for blood transfusion',
                'procedure' => 'Major and minor crossmatch using donor and recipient blood',
                'sample_type' => 'Blood (EDTA and Serum)',
                'cost' => 300.00,
                'turnaround_time' => 4,
                'unit' => 'N/A',
                'normal_values' => 'Compatible (No agglutination)',
                'reference_ranges' => json_encode(['result' => ['values' => ['Compatible', 'Incompatible']]]),
                'parameters' => json_encode(['major_crossmatch' => ['name' => 'Major Crossmatch', 'unit' => ''], 'minor_crossmatch' => ['name' => 'Minor Crossmatch', 'unit' => ''], 'donor_group' => ['name' => 'Donor Blood Group', 'unit' => ''], 'recipient_group' => ['name' => 'Recipient Blood Group', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'COOMBS-D',
                'name' => 'Direct Coombs Test',
                'category' => 'Special',
                'description' => 'Detection of antibodies on RBC surface',
                'procedure' => 'Direct antiglobulin test (DAT)',
                'sample_type' => 'Blood (EDTA)',
                'cost' => 350.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['result' => ['name' => 'Direct Coombs', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'COOMBS-I',
                'name' => 'Indirect Coombs Test',
                'category' => 'Special',
                'description' => 'Detection of antibodies in serum',
                'procedure' => 'Indirect antiglobulin test (IAT)',
                'sample_type' => 'Blood (Serum)',
                'cost' => 350.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Negative',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['result' => ['name' => 'Indirect Coombs', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'MULTIDRUG',
                'name' => 'Multi-Drug Test (12 Panel)',
                'category' => 'Special',
                'description' => 'Screening for multiple drugs of abuse',
                'procedure' => 'Immunoassay',
                'sample_type' => 'Urine',
                'cost' => 800.00,
                'turnaround_time' => 8,
                'unit' => 'N/A',
                'normal_values' => 'Negative for all drugs',
                'reference_ranges' => json_encode(['result' => ['values' => ['Negative', 'Positive']]]),
                'parameters' => json_encode(['amphetamine' => ['name' => 'Amphetamine', 'unit' => ''], 'cocaine' => ['name' => 'Cocaine', 'unit' => ''], 'opiates' => ['name' => 'Opiates', 'unit' => ''], 'thc' => ['name' => 'THC', 'unit' => ''], 'benzodiazepines' => ['name' => 'Benzodiazepines', 'unit' => '']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'PSA',
                'name' => 'PSA (Prostate Specific Antigen)',
                'category' => 'Special',
                'description' => 'Tumor marker for prostate cancer screening',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 600.00,
                'turnaround_time' => 8,
                'unit' => 'ng/mL',
                'normal_values' => '<4.0 ng/mL',
                'reference_ranges' => json_encode(['psa' => ['min' => 0, 'max' => 4, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['psa' => ['name' => 'Total PSA', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'AFP',
                'name' => 'Alpha Feto Protein (AFP)',
                'category' => 'Special',
                'description' => 'Tumor marker for liver cancer and fetal abnormalities',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 600.00,
                'turnaround_time' => 8,
                'unit' => 'ng/mL',
                'normal_values' => '<10 ng/mL (Adult)',
                'reference_ranges' => json_encode(['afp' => ['min' => 0, 'max' => 10, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['afp' => ['name' => 'Alpha Feto Protein', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'VIT-D',
                'name' => 'Vitamin D3 (25-OH Vitamin D)',
                'category' => 'Special',
                'description' => 'Measurement of vitamin D status',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 800.00,
                'turnaround_time' => 8,
                'unit' => 'ng/mL',
                'normal_values' => '30-100 ng/mL (Sufficient)',
                'reference_ranges' => json_encode(['vit_d' => ['min' => 30, 'max' => 100, 'unit' => 'ng/mL']]),
                'parameters' => json_encode(['vit_d' => ['name' => '25-OH Vitamin D', 'unit' => 'ng/mL']]),
                'status' => 'active',
            ],
            [
                'test_code' => 'VIT-B12',
                'name' => 'Vitamin B12',
                'category' => 'Special',
                'description' => 'Measurement of vitamin B12 level',
                'procedure' => 'Chemiluminescent immunoassay',
                'sample_type' => 'Blood (Serum)',
                'cost' => 700.00,
                'turnaround_time' => 8,
                'unit' => 'pg/mL',
                'normal_values' => '200-900 pg/mL',
                'reference_ranges' => json_encode(['vit_b12' => ['min' => 200, 'max' => 900, 'unit' => 'pg/mL']]),
                'parameters' => json_encode(['vit_b12' => ['name' => 'Vitamin B12', 'unit' => 'pg/mL']]),
                'status' => 'active',
            ],
        ];
    }
}