<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Convert risk level string to integer.
     */
    private function getRiskLevelValue(string $riskLevel): int
    {
        return match(strtolower($riskLevel)) {
            'low' => 1,
            'medium' => 2,
            'high' => 3,
            'critical' => 4,
            default => 1,
        };
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks for clean seeding
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        Permission::truncate();
        
        $permissions = $this->getPermissions();
        
        foreach ($permissions as $permissionData) {
            Permission::create([
                'name' => $permissionData['name'],
                'slug' => $this->generateSlug($permissionData['name']),
                'description' => $permissionData['description'],
                'resource' => $permissionData['resource'] ?? null,
                'action' => $permissionData['action'] ?? null,
                'module' => $permissionData['module'],
                'category' => $permissionData['category'],
                'risk_level' => $this->getRiskLevelValue($permissionData['risk_level']),
                'requires_mfa' => $permissionData['requires_mfa'],
                'requires_approval' => $permissionData['requires_approval'] ?? false,
                'is_critical' => $permissionData['is_critical'] ?? false,
            ]);
        }
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $this->command->info('Permissions seeded successfully!');
    }

    /**
     * Generate a slug from a permission name.
     */
    private function generateSlug(string $name): string
    {
        return strtolower(str_replace(['.', ' ', '-'], '_', $name));
    }

    /**
     * Get all permissions based on the RBAC design document.
     * Note: All dot-notation (custom) permissions have been removed.
     * Only standard kebab-case permissions are kept.
     */
    private function getPermissions(): array
    {
        return [
            // User Management Permissions (Standard Kebab-Case)
            [
                'name' => 'view-users',
                'description' => 'View user list',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-users',
                'description' => 'Create new users',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-users',
                'description' => 'Update user information',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-users',
                'description' => 'Delete users',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-user-roles',
                'description' => 'Assign roles to users',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-user-permissions',
                'description' => 'Assign permissions to users',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-users',
                'description' => 'Manage users (create, edit, delete, view all)',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
                'is_critical' => true,
            ],
            [
                'name' => 'manage-permissions',
                'description' => 'Manage roles and permissions system-wide',
                'module' => 'User Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
                'is_critical' => true,
            ],

            // Patient Management Permissions
            [
                'name' => 'view-patients',
                'description' => 'View patient list',
                'module' => 'Patient Management',
                'category' => 'Patient Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-patients',
                'description' => 'Register new patients',
                'module' => 'Patient Management',
                'category' => 'Patient Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-patients',
                'description' => 'Update patient information',
                'module' => 'Patient Management',
                'category' => 'Patient Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-patients',
                'description' => 'Delete patient records',
                'module' => 'Patient Management',
                'category' => 'Patient Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'view-medical-records',
                'description' => 'Access medical records',
                'module' => 'Patient Management',
                'category' => 'Patient Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'write-medical-records',
                'description' => 'Write medical records',
                'module' => 'Patient Management',
                'category' => 'Patient Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],

            // Appointment Management Permissions
            [
                'name' => 'view-appointments',
                'description' => 'View appointment list',
                'module' => 'Appointment Management',
                'category' => 'Appointment Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-appointments',
                'description' => 'Create appointments',
                'module' => 'Appointment Management',
                'category' => 'Appointment Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-appointments',
                'description' => 'Update appointments',
                'module' => 'Appointment Management',
                'category' => 'Appointment Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-appointments',
                'description' => 'Cancel/delete appointments',
                'module' => 'Appointment Management',
                'category' => 'Appointment Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'approve-appointments',
                'description' => 'Approve appointments',
                'module' => 'Appointment Management',
                'category' => 'Appointment Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-all-appointments',
                'description' => 'Manage all appointments',
                'module' => 'Appointment Management',
                'category' => 'Appointment Management',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],

            // Pharmacy Permissions
            [
                'name' => 'view-pharmacy',
                'description' => 'View pharmacy data',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-medicines',
                'description' => 'View medicine inventory',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-medicines',
                'description' => 'Add new medicines',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-medicines',
                'description' => 'Update medicine information',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-medicines',
                'description' => 'Delete medicines',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-inventory',
                'description' => 'Manage inventory',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'adjust-inventory',
                'description' => 'Adjust inventory levels',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'receive-stock',
                'description' => 'Receive stock',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'count-stock',
                'description' => 'Perform stock count',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-sales',
                'description' => 'View sales records',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-sales',
                'description' => 'Create new sales',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-sales',
                'description' => 'Delete sales records',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'void-sales',
                'description' => 'Void sales transactions',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'process-prescriptions',
                'description' => 'Process prescriptions',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-suppliers',
                'description' => 'View suppliers',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-suppliers',
                'description' => 'Create suppliers',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-purchases',
                'description' => 'View purchase orders',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-purchases',
                'description' => 'Create purchase orders',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'receive-purchases',
                'description' => 'Receive purchases',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'cancel-purchases',
                'description' => 'Cancel purchases',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'view-pharmacy-reports',
                'description' => 'View pharmacy reports',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'export-pharmacy-reports',
                'description' => 'Export pharmacy reports',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-alerts',
                'description' => 'View alerts',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-alerts',
                'description' => 'Manage pharmacy alerts',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-medicine-categories',
                'description' => 'Manage medicine categories',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-low-stock-medicines',
                'description' => 'View low stock medicines',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-expired-medicines',
                'description' => 'View expired medicines',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-expired-medicines',
                'description' => 'Delete expired medicines',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'update-medicine-stock',
                'description' => 'Update medicine stock',
                'module' => 'Pharmacy',
                'category' => 'Pharmacy',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],

            // Laboratory Permissions
            [
                'name' => 'view-laboratory',
                'description' => 'View laboratory data',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-lab-tests',
                'description' => 'View available tests',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-lab-tests',
                'description' => 'Create new test types',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-lab-tests',
                'description' => 'Update test configurations',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-lab-tests',
                'description' => 'Delete test types',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'view-lab-test-requests',
                'description' => 'View test requests',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-lab-test-requests',
                'description' => 'Create test requests',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'process-lab-test-requests',
                'description' => 'Process test requests',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'cancel-lab-test-requests',
                'description' => 'Cancel test requests',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-lab-test-results',
                'description' => 'View test results',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-lab-test-results',
                'description' => 'Enter test results',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'validate-lab-test-results',
                'description' => 'Validate test results',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'handle-critical-values',
                'description' => 'Handle critical values',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'view-lab-materials',
                'description' => 'View lab materials',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-lab-materials',
                'description' => 'Create lab materials',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-lab-materials',
                'description' => 'Edit lab materials',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-lab-materials',
                'description' => 'Delete lab materials',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'quality-control',
                'description' => 'Quality control',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-lab-reports',
                'description' => 'View laboratory reports',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'export-lab-reports',
                'description' => 'Export laboratory reports',
                'module' => 'Laboratory',
                'category' => 'Laboratory',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-laboratory',
                'display_name' => 'Manage Laboratory',
                'description' => 'Full access to manage laboratory operations',
                'module' => 'laboratory',
                'category' => 'laboratory',
                'resource' => 'laboratory',
                'action' => 'manage',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],

            // Reports Permissions
            [
                'name' => 'view-reports',
                'description' => 'View reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-reports',
                'description' => 'Create custom reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'export-reports',
                'description' => 'Export reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'scheduled-reports',
                'description' => 'Manage scheduled reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-audit-reports',
                'description' => 'View audit reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-financial-reports',
                'description' => 'View financial reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-hospital-reports',
                'description' => 'View hospital-wide reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-department-reports',
                'description' => 'View department reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-compliance-reports',
                'description' => 'View compliance reports',
                'module' => 'Reports',
                'category' => 'Reports',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],

            // System Configuration Permissions
            [
                'name' => 'view-settings',
                'description' => 'View system settings',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-settings',
                'description' => 'Update system settings',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-backups',
                'description' => 'Manage backups',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'restore-backups',
                'description' => 'Restore from backup',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'critical',
                'requires_mfa' => true,
                'requires_approval' => true,
                'is_critical' => true,
            ],
            [
                'name' => 'maintenance-mode',
                'description' => 'Perform maintenance',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-logging',
                'description' => 'Manage logging settings',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-api-keys',
                'description' => 'Manage API keys',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-integrations',
                'description' => 'Manage integrations',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-cache',
                'description' => 'Manage cache',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-departments',
                'description' => 'Manage departments',
                'module' => 'System Configuration',
                'category' => 'System',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],

            // Security Permissions
            [
                'name' => 'view-audit-logs',
                'description' => 'View audit logs',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-security-alerts',
                'description' => 'View security alerts',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-mfa',
                'description' => 'Manage MFA settings',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-password-policy',
                'description' => 'Manage password policy',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-ip-restrictions',
                'description' => 'Manage IP restrictions',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'manage-sessions',
                'description' => 'Manage sessions',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'medium',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'security-analysis',
                'description' => 'Security analysis',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],
            [
                'name' => 'block-users',
                'description' => 'Block users/IPs',
                'module' => 'Security',
                'category' => 'Security',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],

            // Super Admin Permission
            [
                'name' => 'super-admin',
                'description' => 'Full system access',
                'module' => 'System',
                'category' => 'System',
                'risk_level' => 'critical',
                'requires_mfa' => true,
                'requires_approval' => true,
                'is_critical' => true,
            ],

            // Role Management Permissions
            [
                'name' => 'view-roles',
                'description' => 'View roles',
                'module' => 'Role Management',
                'category' => 'User Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-roles',
                'description' => 'Create roles',
                'module' => 'Role Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'edit-roles',
                'description' => 'Edit roles',
                'module' => 'Role Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'delete-roles',
                'description' => 'Delete roles',
                'module' => 'Role Management',
                'category' => 'User Management',
                'risk_level' => 'critical',
                'requires_mfa' => true,
                'requires_approval' => true,
                'is_critical' => true,
            ],

            // Permission Management Permissions
            [
                'name' => 'view-permissions',
                'description' => 'View permissions',
                'module' => 'Permission Management',
                'category' => 'User Management',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-permissions',
                'description' => 'Create permissions',
                'module' => 'Permission Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'edit-permissions',
                'description' => 'Edit permissions',
                'module' => 'Permission Management',
                'category' => 'User Management',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],
            [
                'name' => 'delete-permissions',
                'description' => 'Delete permissions',
                'module' => 'Permission Management',
                'category' => 'User Management',
                'risk_level' => 'critical',
                'requires_mfa' => true,
                'requires_approval' => true,
                'is_critical' => true,
            ],

            // Doctor Management Permissions
            [
                'name' => 'view-doctors',
                'description' => 'View doctors',
                'module' => 'Doctor Management',
                'category' => 'Hospital',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-doctors',
                'description' => 'Create doctors',
                'module' => 'Doctor Management',
                'category' => 'Hospital',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-doctors',
                'description' => 'Edit doctors',
                'module' => 'Doctor Management',
                'category' => 'Hospital',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-doctors',
                'description' => 'Delete doctors',
                'module' => 'Doctor Management',
                'category' => 'Hospital',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],

            // Department Management Permissions
            [
                'name' => 'view-departments',
                'description' => 'View departments',
                'module' => 'Department Management',
                'category' => 'Hospital',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'create-departments',
                'description' => 'Create departments',
                'module' => 'Department Management',
                'category' => 'Hospital',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'edit-departments',
                'description' => 'Edit departments',
                'module' => 'Department Management',
                'category' => 'Hospital',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'delete-departments',
                'description' => 'Delete departments',
                'module' => 'Department Management',
                'category' => 'Hospital',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => true,
            ],

            // Wallet/Revenue Permissions
            [
                'name' => 'view-wallet',
                'description' => 'View wallet and revenue tracking',
                'module' => 'Wallet',
                'category' => 'Finance',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'manage-wallet',
                'description' => 'Manage wallet transactions',
                'module' => 'Wallet',
                'category' => 'Finance',
                'risk_level' => 'high',
                'requires_mfa' => true,
                'requires_approval' => false,
            ],

            // Dashboard Permissions
            [
                'name' => 'view-dashboard',
                'display_name' => 'View Dashboard',
                'description' => 'Access the main dashboard',
                'module' => 'dashboard',
                'category' => 'Dashboard',
                'resource' => 'dashboard',
                'action' => 'view',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
            [
                'name' => 'view-reception',
                'display_name' => 'View Reception',
                'description' => 'Access the reception module',
                'module' => 'reception',
                'category' => 'Reception',
                'resource' => 'reception',
                'action' => 'view',
                'risk_level' => 'low',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],

            // Audit Permissions
            [
                'name' => 'view-activity-logs',
                'display_name' => 'View Activity Logs',
                'description' => 'View system activity and audit logs',
                'module' => 'audit',
                'category' => 'Audit',
                'resource' => 'activity-logs',
                'action' => 'view',
                'risk_level' => 'medium',
                'requires_mfa' => false,
                'requires_approval' => false,
            ],
        ];
    }
}
