/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.store": [],
    "register": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.update": [],
    "patients.index": [],
    "patients.create": [],
    "patients.store": [],
    "patients.show": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "patients.edit": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "patients.update": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "patients.destroy": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "doctors.index": [],
    "doctors.create": [],
    "doctors.store": [],
    "doctors.show": [
        {
            "name": "doctor",
            "required": true
        }
    ],
    "doctors.edit": [
        {
            "name": "doctor",
            "required": true
        }
    ],
    "doctors.update": [
        {
            "name": "doctor",
            "required": true
        }
    ],
    "doctors.destroy": [
        {
            "name": "doctor",
            "required": true
        }
    ],
    "appointments.index": [],
    "appointments.create": [],
    "appointments.store": [],
    "appointments.show": [
        {
            "name": "appointment",
            "required": true
        }
    ],
    "appointments.edit": [
        {
            "name": "appointment",
            "required": true
        }
    ],
    "appointments.update": [
        {
            "name": "appointment",
            "required": true
        }
    ],
    "appointments.destroy": [
        {
            "name": "appointment",
            "required": true
        }
    ],
    "billing.index": [],
    "billing.create": [],
    "billing.store": [],
    "billing.show": [
        {
            "name": "bill",
            "required": true
        }
    ],
    "billing.edit": [
        {
            "name": "bill",
            "required": true
        }
    ],
    "billing.update": [
        {
            "name": "bill",
            "required": true
        }
    ],
    "billing.destroy": [
        {
            "name": "bill",
            "required": true
        }
    ],
    "pharmacy.medicines.index": [],
    "pharmacy.medicines.create": [],
    "pharmacy.medicines.store": [],
    "pharmacy.medicines.show": [
        {
            "name": "medicine",
            "required": true
        }
    ],
    "pharmacy.medicines.edit": [
        {
            "name": "medicine",
            "required": true
        }
    ],
    "pharmacy.medicines.update": [
        {
            "name": "medicine",
            "required": true
        }
    ],
    "pharmacy.medicines.destroy": [
        {
            "name": "medicine",
            "required": true
        }
    ],
    "pharmacy.stock.index": [],
    "pharmacy.stock.report": [],
    "pharmacy.stock.alerts": [],
    "pharmacy.sales.index": [],
    "pharmacy.sales.create": [],
    "pharmacy.sales.store": [],
    "pharmacy.sales.show": [
        {
            "name": "sale",
            "required": true
        }
    ],
    "pharmacy.purchase-orders.index": [],
    "pharmacy.purchase-orders.create": [],
    "pharmacy.purchase-orders.store": [],
    "pharmacy.purchase-orders.show": [
        {
            "name": "purchaseOrder",
            "required": true
        }
    ],
    "pharmacy.purchase-orders.edit": [
        {
            "name": "purchaseOrder",
            "required": true
        }
    ],
    "pharmacy.purchase-orders.update": [
        {
            "name": "purchaseOrder",
            "required": true
        }
    ],
    "pharmacy.purchase-orders.destroy": [
        {
            "name": "purchaseOrder",
            "required": true
        }
    ],
    "pharmacy.purchase-orders.update-status": [
        {
            "name": "purchaseOrder",
            "required": true
        }
    ],
    "pharmacy.alerts.index": [],
    "pharmacy.alerts.pending": [],
    "pharmacy.alerts.resolved": [],
    "pharmacy.alerts.trigger-check": [],
    "pharmacy.alerts.update-status": [
        {
            "name": "alert",
            "required": true
        }
    ],
    "laboratory.lab-tests.index": [],
    "laboratory.lab-tests.create": [],
    "laboratory.lab-tests.store": [],
    "laboratory.lab-tests.show": [
        {
            "name": "labTest",
            "required": true
        }
    ],
    "laboratory.lab-tests.edit": [
        {
            "name": "labTest",
            "required": true
        }
    ],
    "laboratory.lab-tests.update": [
        {
            "name": "labTest",
            "required": true
        }
    ],
    "laboratory.lab-tests.destroy": [
        {
            "name": "labTest",
            "required": true
        }
    ],
    "laboratory.lab-test-results.index": [],
    "laboratory.lab-test-results.create": [],
    "laboratory.lab-test-results.store": [],
    "laboratory.lab-test-results.show": [
        {
            "name": "labTestResult",
            "required": true
        }
    ],
    "laboratory.lab-test-results.edit": [
        {
            "name": "labTestResult",
            "required": true
        }
    ],
    "laboratory.lab-test-results.update": [
        {
            "name": "labTestResult",
            "required": true
        }
    ],
    "laboratory.lab-test-results.destroy": [
        {
            "name": "labTestResult",
            "required": true
        }
    ],
    "reports.index": [],
    "reports.patient": [],
    "reports.doctor": [],
    "reports.appointment": [],
    "reports.billing": [],
    "reports.pharmacy-sales": [],
    "reports.lab-test": [],
    "admin.dashboard": [],
    "admin.users.index": [],
    "admin.users.create": [],
    "admin.users.store": [],
    "admin.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.permissions.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.permissions.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
